version: '3.8'

services:
  pubsub:
    container_name: pubsub_v1
    image: gcloud/pubsub:v1
    build: 
      context: .
    environment:
      - PUBSUB_PROJECT_ID=my-project-1
    ports:
      - "8085:8085"
