version: '3.8'

services:
  pubsub:
    container_name: pubsub_v1
    image: sneyt04/gcloud-pubsub:1.0
    build: 
      context: .
      args:
        - PUBSUB_PROJECT_ID=my-project-1
    ports:
      - "8085:8085"
